namespace: timhatdiehandandermaus

deployment:
  name: plex-resolver
  image: ghcr.io/tim-hat-die-hand-an-der-maus/plex-resolver:__TAG__
  imagePullPolicy: Always
  revisionHistoryLimit: 1
  replicas: 2
  ports:
    - 8080
  labels:
    app: plex-resolver
  requests:
    cpu: 50m
    memory: 10Mi
  limit:
    cpu: 300m
    memory: 50Mi

service:
  name: plex-resolver
  port: 80
  targetPort: 8080
  appSelector: plex-resolver

secret:
  name: rabbitmq
  token: __PLEX_TOKEN__

configmap:
  name: plex-resolver
  plex:
    url: https://plex.carstens.tech
