apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
data:
  PLEX_TOKEN: "{{ .Values.secret.token }}"
  config.toml: |
    {{- range .Values.secret.plexServers }}
    [[server]]
    name = {{ .name | quote }}
    url = {{ .url | quote }}
    token = {{ .token | quote }}
    {{- end }}
