apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
stringData:
  config.toml: |
    {{- range .Values.secret.plexServers }}
    [[server]]
    name = {{ .name | quote }}
    url = {{ .url | quote }}
    token = {{ .token | b64dec | quote }}
    {{- end }}
