name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint --strict

  build_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/tim-hat-die-hand-an-der-maus/plex-resolver:${GITHUB_SHA} .
      - name: Push the tagged Docker image
        run: docker push ghcr.io/tim-hat-die-hand-an-der-maus/plex-resolver:${GITHUB_SHA}

  deploy:
    runs-on: ubuntu-latest
    needs: [build_push_docker, lint]
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: update tag in manifest.yml
        run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - run: sed -i -e "s#__TORBEN_PLEX_TOKEN__#${{ secrets.PLEX_TOKEN }}#g" values.yaml
      - name: install helm chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade plex-resolver . --install --namespace=timhatdiehandandermaus --atomic
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
