name: Lint helm chart

on:
  push:
    branches:
      - '!master'
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint --strict
